import Head from 'next/head';
import { client } from "../lib/client";
import { Product, FooterBanner, HeroBanner } from "../components";

export default function Home({ products, bannerData }) {
  return (
    <div>
      <Head>
        <title>BuzzEar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner heroBanner={bannerData.length && bannerData[0]} />
      {console.log(products)}
      <div className="products-heading">
        <h2>Best Seller Products</h2>
        <p>Sound systems for <b>all moods and events</b></p>
      </div>

      <div className="products-container">
        {products?.map((product)=> 
          <Product key={product._id} product={product} />
        )}
      </div>
      
      <FooterBanner footerBanner={bannerData && bannerData[0]} />
    </div>
  )
}


export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData }
  }
}
